# These are supported funding model platforms

github: ELMOURABEA
patreon: ELMOURABEA
open_collective: ELMOURABEA
ko_fi: ELMOURABEA
liberapay: ELMOURABEA
polar: ELMOURABEA
buy_me_a_coffee: ELMOURABEA
custom: ["https://github.com/sponsors/ELMOURABEA"]
