name: Python package (Conda)

on:
  push:
    branches: [ active-branch]
  pull_request:
    branches: [ active-branvh]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          auto-update-conda: true
          activate-environment: activbot-ci
          environment-file: environment.yml
          use-mamba: true

      - name: Install dependencies (fallback)
        if: failure() || success()
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true

      - name: Lint
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8 . || true
          fi

      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q || true
          fi
