name: CI

on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
name: Python package (Conda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          auto-update-conda: true
          activate-environment: activbot-ci
          environment-file: environment.yml
          use-mamba: true

      - name: Install dependencies (fallback)
        if: failure() || success()
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true

      - name: Lint
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8 . || true
          fi

      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q || true
          fi
